package com.wlmd.discord_bot.listeners;

import org.springframework.stereotype.Component;
import jakarta.validation.constraints.NotNull;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.events.guild.GuildJoinEvent;
import net.dv8tion.jda.api.events.guild.GuildLeaveEvent;
import com.wlmd.discord_bot.service.LoadGuildMembersService;
import com.wlmd.discord_bot.service.AddDeleteGuildService;

// Currently only used to log into the console when the bot enters and leaves a server and loads the server users into the database.
// TODO: The code is very raw. Check the exceptions that may be generated by loadUsers and see if it is better to handle them here or in the service.

@Component
public class GuildJoinLeaveEventListener extends ListenerAdapter {

	private final LoadGuildMembersService loadServerUsers;
	private final AddDeleteGuildService addDeleteGuildService;

	
	public GuildJoinLeaveEventListener(LoadGuildMembersService loadServerUsers, AddDeleteGuildService addDeleteGuildService) {
		
		this.loadServerUsers = loadServerUsers;
		this.addDeleteGuildService = addDeleteGuildService;

	}

	@Override
	public void onGuildJoin(@NotNull GuildJoinEvent event) {
		
		 Long serverId = event.getGuild().getIdLong();
		 String serverName = event.getGuild().getName();		 
		 String serverJoinedDate = event.getGuild().getTimeCreated().toString();
		 String timeCreated = event.getGuild().getTimeCreated().toString();
		 int memberCount =  event.getGuild().getMemberCount();

		 System.out.println("Server ID: " + serverId);
		 System.out.println("The bot has joined the server: " + serverName);		 
		 System.out.println("Date: " + serverJoinedDate);
		 System.out.println();
		 addDeleteGuildService.addGuild(event);
		 loadServerUsers.loadUsers(event);

	}
	
	@Override
	public void onGuildLeave(@NotNull GuildLeaveEvent event) {
		
		 String serverName = event.getGuild().getName();
		 String serverId = event.getGuild().getId();
		 String serverLeaveDate = event.getGuild().getTimeCreated().toString();
		 System.out.println("The bot left the server:  " + serverName);
		 System.out.println("Server ID: " + serverId);
		 System.out.println("Date: " + serverLeaveDate);
		 System.out.println();
		 addDeleteGuildService.deleteGuild(event);

	}
}
