version: '3.8'
networks:
  discordBotNetwork:
    driver: bridge


services:
  db:
    image: postgres:13
    container_name: discordBotPostgres
    restart: always
    environment:
      - POSTGRES_USER=welli
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=discordBotDb
    ports:
      - "5432:5432"
    volumes:
      - pgData:/var/lib/postgresql/data
    networks:
      - discordBotNetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=wellingtonluanmd@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=senha123
    volumes:
      - pgadminData:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - discordBotNetwork

  app:
    build: .
    container_name: discordBotApp
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/discordBotDb
      - SPRING_DATASOURCE_USERNAME=welli
      - SPRING_DATASOURCE_PASSWORD=senha123
    ports:
      - "8087:8087"
    volumes:
      - ./src:/app/src           
      - ./target:/app/target     
      - ~/.m2:/root/.m2          
    depends_on:
      - db
    networks:
      - discordBotNetwork


volumes:
  pgData:
  pgadminData:
